# frozen_string_literal: true
source "https://rubygems.org"

# Gem
gem 'interactor_ui_automation', path: '../gem'

# Core
gem 'minitest'
gem 'rake'

# Selenium
gem 'chromedriver-helper'
gem 'selenium-webdriver'
