task :server do
  # serve static files for use with test suite
  `ruby -run -ehttpd ./site -p8000`
end

task :test, [:pattern] do |t, args|
  # start shared driver instance
  require_relative './tests/driver_provider'
  driver = DriverProvider.instance.driver
  # terminate shared driver instance after tests complete
  require 'minitest'
  Minitest.after_run do
    driver.quit
  end

  # register tests to execute (via Minitest#autorun) at process exit
  pattern = args.fetch(:pattern, './tests/**/test_*.rb')
  file_paths = Dir.glob(pattern)
  puts "Files: #{file_paths.sort.join(' ')}"
  file_paths.each { |file| require_relative(file) }
end

task default: :test
