task :default => :test
task :test do
  pattern = ARGV[1] || './tests/**/test_*.rb'
  Dir.glob(pattern).each { |file| require file }
end

task :server do
  # serve static files for use with test suite
  `ruby -run -ehttpd ./site -p8000`
end
